import { Poppins, Inter } from "next/font/google"; // Dono fonts import karein
import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import "./globals.css";

// Poppins font configuration
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

// Inter font configuration
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "200", "100"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className} ${inter.className}`}>
      {/* By default Poppins font use hoga */}
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
